global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'bash_metrics'
    static_configs:
      - targets: ['pushgateway:9091']
      
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - "alertmanager:9093"

rule_files:
  - "alert.rules.yml"